### ISSUE TITLE
run the program on a folder in ubuntu to generate a vcard business card thumbnail for each vcard

### ISSUE THREAD

**Issue by largewebsite** [l0b0/vcard#41]
interested in using this program to create thumbnails that look like business cards with a photo and basic information to show this thumbnail on all the vcards in the folder.

**Comment by l0b0** [comment]
I'm afraid this is nowhere near the goal of this project. But you are of course welcome to use the source code according to the license to develop something like this.

**Comment by largewebsite** [comment]
thank you
